Fix/clean up repo
splunk/SC4SNMP-UI pull request #16
Opened 2023-06-07 14:13 UTC by wojtekzyla

2023-06-16 09:14 UTC, omrozowicz-splunk approved these changes

2023-06-20 08:02 UTC, omrozowicz-splunk requested changes

2023-06-20 08:02 UTC, omrozowicz-splunk commented on .github/workflows/ci-build.yaml
> +            type=ref,event=pr
not sure if we need to build pr images, I think this is too much

2023-06-20 08:02 UTC, omrozowicz-splunk commented on .github/workflows/ci-release.yaml
> +            type=ref,event=pr
same thing with pr tag

2023-06-20 08:02 UTC, omrozowicz-splunk commented on .github/workflows/ci-release.yaml
> +            type=ref,event=pr
same here

2023-06-20 16:27 UTC, wojtekzyla commented on .github/workflows/ci-build.yaml
> +            type=ref,event=pr
changed

2023-06-20 16:27 UTC, wojtekzyla commented on .github/workflows/ci-release.yaml
> +            type=ref,event=pr
changed

2023-06-20 16:27 UTC, wojtekzyla commented on .github/workflows/ci-release.yaml
> +            type=ref,event=pr
changed

2023-06-21 14:40 UTC, omrozowicz-splunk approved these changes

2023-06-22 07:39 UTC, merged

2023-07-05 08:51 UTC, srv-rr-github-token commented
:tada: This PR is included in version 1.0.0-beta.1 :tada:

The release is available on [GitHub release](https://github.com/splunk/SC4SNMP-UI/releases/tag/v1.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: